opti: enable optimizer
cometh-hq/p256-signer pull request #15
Opened 2023-10-19 14:25 UTC by obatirou

Enable optimizer to reduce gas consumption of `isValidSignature`:

- without optimizer: 395941
![Capture d’écran 2023-10-19 à 16 21 32](https://github.com/cometh-game/p256-signer/assets/92337658/8c7b977c-813b-4ee8-b852-4720e0ce664a)
- with optimizer: 222404
![Capture d’écran 2023-10-19 à 16 21 21](https://github.com/cometh-game/p256-signer/assets/92337658/ffd70c05-685f-433f-9544-6b8fa273be74)

It will match config in FCL library.

2023-10-19 15:05 UTC, Kelvyne requested changes, later dismissed
I think the issue here is that it doesn't use hardhat config. Why is that ?

2023-10-19 15:08 UTC, obatirou commented
> I think the issue here is that it doesn't use hardhat config. Why is that ?

Oh you are right. It is part of foundry unit tests and it uses the foundry.toml configuration which do not have the optimizer enabled.
Anyway, foundry config and hardhat config should be matched.

2023-10-25 07:58 UTC, LaurentSalou approved these changes

2023-10-25 08:17 UTC, yoanslvy commented
LGTM

2023-10-25 08:32 UTC, merged